In [6]:
import csv
import pandas as pd
Buses=pd.read_csv('C:\\Users\\hanno\\OneDrive\\Documents\\Custom Office Templates\\ip_project.csv',index_col=0)
Buses

,Date,Bus_No,Passenger_Name,Phone_No,Aadhar_No,No_Of_Passenger,Destination_From,Destination_To,Duration,Seat_Type,Price,Total_Price
Passenge_No,,,,,,,,,,,,
1,1st August 2024,101,Lal Patel,6986533598,727783774214,1,Coimbatore,Amritsar,48 hours,Standard,2500,2500.0
2,3rd August 2024,126,Raj,8368609044,684932071480,3,Chennai,Bangalore,7 hours,Luxury,1500,4500.0
3,3rd August 2024,126,Tom,4753819025,739201739021,2,Chennai,Bangalore,7 hours,Sleeper,900,1800.0
4,3rd August 2024,126,Sohan,9025671936,860262959217,1,Chennai,Bangalore,7 hours,Standard,600,600.0
5,1st August 2024,112,Rahul,9015782340,748102351967,4,Kannyakumari,Coimbatore,8 hours,Luxury,1500,6000.0
6,1st August 2024,112,Shiva,7391024517,931629017891,1,Kannyakumari,Coimbatore,8 hours,Standard,800,800.0
7,2nd August 2024,132,Raju,7910347196,201789174516,2,Kochi,Trivandrum,7 hours,Recline,700,1400.0
8,2nd August 2024,132,Seetha,6801537198,820185610927,1,Kochi,Trivandrum,7 hours,Standard,500,500.0
9,3rd August 2024,108,Abdul,9103728547,759014276018,6,Thirunelveli,Madurai,3 hours,Standard,350,2100.0
10,2nd August 2024,122,Abraham,2710561839,371058201592,1,Mumbai,Bangalore,20 hours,Luxury,2500,2500.0
11,2nd August 2024,122,Reeta,9016278156,515378915379,2,Mumbai,Bangalore,20 hours,Standard,1200,2400.0
12,2nd August 2024,122,Jesica,8102574193,679203518946,1,Mumbai,Bangalore,20 hours,Standard,1200,1200.0
13,31st July 2024,129,Abdula,8301839173,901253747629,3,Trivandrum,Ernakulam,6 hours,Recline,600,1800.0
14,30th July 2024,116,Ahmed,8309830273,282497347836,1,Hyderabad,Pune,10 hours,Standard,1000,1000.0
15,31st July 2024,119,Raja,7370973732,283133239737,3,Goa,Mumbai,10 hours,Luxury,10500,NaN
16,1st August 2024,112,Rohan,7249990647,975860260296,2,Kannyakumari,Coimbatore,8 hours,Sleeper,1200,2400.0
17,31st July 2024,119,Sona,6274698018,712906016364,3,Goa,Mumbai,10 hours,Luxury,2000,6000.0
18,29th July 2024,143,Shawn,6462426877,698576452146,1,Kollam,Trivandrum,2 hours,Recline,300,300.0
19,31st July 2024,119,Aravind,6473811762,995978396293,2,Goa,Mumbai,10 hours,Sleeper,1200,2400.0
20,3rd August 2024,108,Chris,8265363278,689034606558,1,Thirunelveli,Madurai,3 hours,Standard,350,350.0
21,30th July 2024,116,Satheesh,6598368296,982602629475,2,Hyderabad,Pune,10 hours,Standard,1000,2000.0
22,29th July 2024,143,Anshad,6489692684,479202598849,3,Kollam,Trivandrum,2 hours,Standard,150,300.0
23,2nd August 2024,132,Sam,5428482718,638103635578,1,Kochi,Trivandrum,7 hours,Recline,800,800.0
24,31st July 2024,129,John,6587555344,579076434279,2,Trivandrum,Ernakulam,6 hours,Recline,600,600.0
25,31st July 2024,129,Rajesh,6462620187,823659371029,5,Trivandrum,Ernakulam,6 hours,Standard,500,2500.0